### ISSUE TITLE
Thanks + a couple of suggestions

### ISSUE THREAD

**Issue by JoCat** [koddr/yandex-music-desktop#10]
I wanted to thank you for the app. Such a simple yet necessary solution.

I will make my small contribution, an example of Desktop Entry for Linux (can be added to readme):
```desktop
[Desktop Entry]
Type=Application
Name=Yandex Music
# Example path to icon (Can be taken from this repository https://github.com/koddr/yandex-music-desktop/blob/master/static/macOS/yamusic_desktop.png)
Icon=/home/apps/YandexMusic/yamusic_desktop.png
# Example path to app
Exec=/home/apps/YandexMusic/yamusic_desktop
Categories=Audio;
```

And I would also like to offer 2 features that would not be bad to implement:

- Minimize to tray
- Save session after login

_You can also autobuild using Github Actions_

**UPD**
I saw a couple of problems in closed issues that are quite relevant (for example, saving the session)
I can help in my free time :grin:

**Comment by koddr** [comment]
Hi,

At the moment, unfortunately, I cannot fully support the project, so any help in the development of the project will be met with great gratitude! 

If you have time to send a **PR**, then I will be happy to consider and accept it. 

Thank you for your interest in the project ❤️

**Comment by JoCat** [comment]
Yeah interesting 🤔
on windows the session is saved
![image](https://user-images.githubusercontent.com/13483132/168386122-0de5241d-175d-4263-969d-6e037acf1de1.png)

**Comment by tooweb** [comment]
Does not work any more(

**Comment by JoCat** [comment]
> Does not work any more(

What operating system are you using?

**Comment by tooweb** [comment]
> > Does not work any more(
> 
> What operating system are you using?

Windows 11 pro
21H2
22000.1574

**Comment by JoCat** [comment]
Check this version, it should work

[Yandex.Music Desktop.zip](https://github.com/koddr/yandex-music-desktop/files/10834167/Yandex.Music.Desktop.zip)

**Comment by tooweb** [comment]
> Check this version, it should work
> 
> [Yandex.Music Desktop.zip](https://github.com/koddr/yandex-music-desktop/files/10834167/Yandex.Music.Desktop.zip)

Thank you very much, it really works, and in conjunction with 4t-min, minimizing to tray works!
