### ISSUE TITLE
Support Linux?

### ISSUE THREAD

**Issue by vn971** [koddr/yandex-music-desktop#3]
First of all, thanks for the project. Adding support for Linux would be awesome!

As an ArchLinux user myself, I can certainly help getting it published in AUR for more visibility, for example.

**Comment by koddr** [comment]
@vn971 thx for using 😉 

Main problem for port to Linux is using CGO by webview package, because I build binary from macOS. If you have time, can you please try to make binary for Linux at your PC?

It's easy (from root folder of repository):

```bash
# Check Go version: 1.13+ will be okay

# Install xgo
$ go get -u github.com/karalabe/xgo

# Try to build binary for Linux
$ xgo -out ./build/Linux/yamusic_desktop --targets=linux/amd64 github.com/koddr/yandex-music-desktop
```

If everything wrong, please tell me 👍

**Comment by vn971** [comment]
Tried it now. It somewhy complains about docker:

```
go get -u github.com/karalabe/xgo

~/go/bin/xgo -out ./build/Linux/yamusic_desktop --targets=linux/amd64 github.com/koddr/yandex-music-desktop
Checking docker installation...
Client:
 Version:           19.03.5-ce
 API version:       1.40
 Go version:        go1.13.4
 Git commit:        633a0ea838
 Built:             Fri Nov 15 03:19:09 2019
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at tcp://127.0.0.1:2375. Is the docker daemon running?
2020/02/05 17:34:27 Failed to check docker installation: exit status 1.
```

Does it need docker to build? :thinking:

**Comment by vn971** [comment]
Ah, and almost forgot
```
go version
go version go1.13.7 linux/amd64
```

**Comment by vn971** [comment]
(@koddr not using yet, but would be happy to, especially if I can eventually somehow bring in a feature that I want in it. The feature is to be able to auto-stop after each played track, when asked to.)

**Comment by koddr** [comment]
> Does it need docker to build? 🤔

Oh, yes! Sorry, I forgot that. I use Docker every day for work and I didn't think anyone might not have it. 😉 

Can you please run simple `go build ./...` and try to run binary?

**Comment by vn971** [comment]
@koddr I'm a bit confused sorry. Where should I run it, in what directory? Should I clone this repo and run it there? Or the `xgo` repo? Or?

I do have docker, but I prefer not to use it generally as it is a security disaster. Giving access to docker is the same as giving root access to your system (literally, documented so by docker as well).

**Comment by koddr** [comment]
Oh, my bad.

1. Download this repo (by `git clone` or [this direct link](https://github.com/koddr/yandex-music-desktop/archive/master.zip));
2. Unpack and go to downloaded folder;
3. Try to run:

```bash
$ go build ./...
```

**Comment by vn971** [comment]
I was able to successfully build the app! Does it provide any advantages over the web version though, except being in a stand-alone window (like you can get with running `firefox -p`)? I thought there'll be a possibility to e.g. configure global shortcuts. Is there such a thing, maybe I missed it?

**Comment by koddr** [comment]
> I was able to successfully build the app!

Wow, good news! Now, I need Linux on VM to complete build for this arch. 

Thx! 👍 

> Does it provide any advantages over the web version though, except being in a stand-alone window (like you can get with running `firefox -p`)? I thought there'll be a possibility to e.g. configure global shortcuts. Is there such a thing, maybe I missed it?

This desktop app support media keys on MacBook and other keyboards. Also, all of default browser feature of your OS can work with app.

Not sure about `global shortcuts`, because I'm not using Linux at home OS (only on server side).

**Comment by vn971** [comment]
OK, understood. Thanks for the instructions! I think it's safe to add Linux to the "works on" section then, since it can be built and runs just fine (as far as I can tell).

I guess I'll use the browser version for now myself tho. Good luck with the project!
