### ISSUE TITLE
Keep authentication after app restart

### ISSUE THREAD

**Issue by antonsoroko** [koddr/yandex-music-desktop#4]
**Describe the bug**
Keep authentication after app restart. Currently user have to login every time he/she open app. At least on Linux.

**To Reproduce**

1. open app
2. do auth
3. restart app - you have to do auth again

**Expected behavior**
Keep authentication.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Kubuntu
- Version 20.10

**Additional context**
Thank you.

**Comment by koddr** [comment]
Hi, @antonsoroko 

Sorry, but on my Linux machine (Arch) everything is okay. Could be a problem with the default browser that is installed on your OS?

**Comment by antonsoroko** [comment]
Hi. Thank for the reply.
Hard to tell since there is no log/debug mode.
I tried to switch browsers (chrome/firefox/opera) with KDE UI (similar to `xdg-settings set default-web-browser`) and terminal (`sudo update-alternatives --config x-www-browser`) and via env (e.g. `BROWSER=/usr/bin/firefox yamusic_desktop`) - same behavior.

**Comment by antonsoroko** [comment]
is there a way to enable debug/verbose mode maybe?
