### ISSUE TITLE
Prev/Next buttons don't work

### ISSUE THREAD

**Issue by meqabayt** [koddr/yandex-music-desktop#5]
**Is your feature request related to a problem? Please describe.**
Prev/Next buttons don't work.

**Describe the solution you'd like**
I know that this is a Yandex music issue and you can not change the song to prev/next with Macos fn buttons (only play pause works). But there are some extensions which can provide this functionality for Yandex music. I think somehow you can do that also. I can also contribute if I can find free time.

![image](https://user-images.githubusercontent.com/2946210/107486804-e5d6da80-6b9e-11eb-891e-987a533a0fd2.png)

**Comment by koddr** [comment]
@meqabayt thanks for issue.

Hmm.. need some investigation, because I don't found any rather solution :(
