### ISSUE TITLE
if display resolution is scaled, window content is blurred

### ISSUE THREAD

**Issue by foogaz** [koddr/yandex-music-desktop#8]
**Describe the bug**
if display resolution is scaled, window content is blurred

**To Reproduce**

1. Go to 'System Preferences'
2. Click on 'Displays'
3. Click on 'Resolution: Scaled'
4. Click on right button with example image
5. Open app: window content is blurred

**Expected behavior**

**Screenshots**
<img width="780" alt="Screenshot 2021-11-22 at 11 48 09" src="https://user-images.githubusercontent.com/13391576/142834963-f0571753-beb3-4ea1-8d5a-94519e145cc7.png">
<img width="912" alt="Screenshot 2021-11-22 at 11 48 18" src="https://user-images.githubusercontent.com/13391576/142834984-d9276bac-876c-48d1-818f-1831cbfd85f2.png">

**Desktop (please complete the following information):**
- macOS Mojave
- 10.14.6

**Comment by koddr** [comment]
Duplicate #1 and #7.
