### ISSUE TITLE
An old browser error happened 

### ISSUE THREAD

**Issue by ghost** [koddr/yandex-music-desktop#9]
**Describe the bug**
Tell me that my browser is old

**To Reproduce**

1- Login to Ya music
2- Shows me script error, i click yes button
3- Error happens

**Expected behavior**
Yandex Music open

**Screenshots**
![image](https://user-images.githubusercontent.com/57063825/144128690-58d0372b-0da2-44d8-b428-73542f36f782.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Version 19044.1387

**Comment by koddr** [comment]
Hi,

Please read [this](https://github.com/koddr/yandex-music-desktop#for-windows-10-users-who-removed-microsoft-edge-browser) topic from the official README.

**Comment by Mikey1993** [comment]
I haven't removed MS Edge browser from my computer but this error popped when trying to use the program.
After compiling the code myself I could start this program without any errors.

**Comment by JoCat** [comment]
Perhaps cross-compiling is using an older version of Edge/webview

**Comment by JoCat** [comment]
I compiled the program according to the information from the readme, now it requires a dll, as in the latest versions of webview (https://github.com/webview/webview#distributing-webview-apps)
It seems that in the new versions they decided to fix it, but so far I haven’t really delved into it (https://github.com/webview/webview#windows-build-script-details)
![image](https://user-images.githubusercontent.com/13483132/168384830-445f470f-f38b-4ca8-b31e-bf13d21d4c16.png)

After adding them everything works
![image](https://user-images.githubusercontent.com/13483132/168385571-8d214be8-0efe-43b6-b062-0216b1cf740b.png)

**Comment by JoCat** [comment]
Yep, inactive author

**Comment by koddr** [comment]
Added fix in #11
